# fly.toml app configuration file generated for tetrus on 2024-10-12T22:38:15+06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tetrus'
primary_region = 'waw'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 2
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
